add a public index page
so you can go to /public/

http://localhost:8080/public/

[kushal@ideapadflex-kushal openroom]$ npm install -g sass
/home/kushal/.nvm/versions/node/v13.12.0/bin/sass -> /home/kushal/.nvm/versions/node/v13.12.0/lib/node_modules/sass/sass.js
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.1.2 (node_modules/sass/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

+ sass@1.26.3
added 15 packages from 18 contributors in 2.05s
[kushal@ideapadflex-kushal openroom]$ dnf info sass
Fedora Modular 31 - x86_64 - Updates                                                                                                                   61 kB/s |  16 kB     00:00
Fedora 31 - x86_64 - Updates                                                                                                                           30 kB/s |  12 kB     00:00
Error: No matching Packages to list
[kushal@ideapadflex-kushal openroom]$ dnf search sass
Last metadata expiration check: 0:00:08 ago on Wed 08 Apr 2020 07:18:34 PM MDT.
============================================================================ Name & Summary Matched: sass ============================================================================
rubygem-sassc.x86_64 : Use libsass with Ruby!
libsass-devel.i686 : Development files for libsass
libsass-devel.x86_64 : Development files for libsass
python3-libsass.x86_64 : Python bindings for libsass
libsass.i686 : C/C++ port of the Sass CSS precompiler
libsass.x86_64 : C/C++ port of the Sass CSS precompiler
rubygem-sass-doc.noarch : Documentation for rubygem-sass
rubygem-sassc-doc.noarch : Documentation for rubygem-sassc
sassc.x86_64 : Wrapper around libsass to compile CSS stylesheet
evolution-spamassassin.x86_64 : SpamAssassin plugin for Evolution
rubygem-sass-rails-doc.noarch : Documentation for rubygem-sass-rails
rubygem-sass-rails.noarch : Sass adapter for the Rails asset pipeline
rubygem-jekyll-sass-converter.noarch : Basic Sass converter for Jekyll
vim-syntastic-sass.noarch : A syntax checker for sass programming language
claws-mail-plugins-spamassassin.x86_64 : Spamassassin plugin for Claws Mail
rubygem-bootstrap-sass-doc.noarch : Documentation for rubygem-bootstrap-sass
rubygem-jekyll-sass-converter-doc.noarch : Documentation for rubygem-jekyll-sass-converter
spamassassin-iXhash2.noarch : SpamAssassin plugin to lookup e-mail checksums in blacklists
rubygem-sass-twitter-bootstrap-doc.noarch : Documentation for rubygem-sass-twitter-bootstrap
golang-github-wellington-libsass-devel.noarch : Go wrapper for libsass, the only Sass 3.5 compiler for Go
rubygem-bootstrap-sass.noarch : Twitter's Bootstrap, converted to Sass and ready to drop into Rails or Compass
================================================================================= Name Matched: sass =================================================================================
sassist.noarch : Dell SupportAssist log collector
spamassassin.x86_64 : Spam filter for email which can be invoked from mail delivery agents
rubygem-sass.noarch : A powerful but elegant CSS compiler that makes CSS fun again
rubygem-sass-twitter-bootstrap.noarch : Gem of the Twitter Bootstrap
=============================================================================== Summary Matched: sass ================================================================================
z80dasm.x86_64 : Z80 Disassembler
libdasm.i686 : Simple x86 disassembly library
libdasm.x86_64 : Simple x86 disassembly library
golang-github-vbatts-tar-split.x86_64 : Tar archive assembly/disassembly
golang-github-vbatts-tar-split-devel.noarch : Tar archive assembly/disassembly
spamass-milter.x86_64 : Milter (mail filter) for spamassassin
udis86.i686 : A disassembler library for x86 and x86-64
udis86.x86_64 : A disassembler library for x86 and x86-64
golang-github-bep-tocss-devel.noarch : Simple to use Go API for LibSass. Uses CGO
d52.x86_64 : Disassemblers for 8051, 8048, and Z80 families
python2-pydasm.x86_64 : Python module for disassembling x86 machine code
spampd.noarch : Transparent SMTP/LMTP proxy filter using spamassassin
amavis.noarch : Email filter with virus scanner and spamassassin support
perl-NetPacket-LLC.noarch : Assemble and disassemble IEEE 802.3 LLC protocol packets
perl-NetPacket.noarch : Assemble/disassemble network packets at the protocol level
examiner.noarch : Utility to disassemble and comment foreign executable binaries
perl-NetPacket-SpanningTree.noarch : Assemble and disassemble IEEE 802.1D Spanning Tree protocol packets
capstone.x86_64 : A lightweight multi-platform, multi-architecture disassembly framework
capstone.i686 : A lightweight multi-platform, multi-architecture disassembly framework
perl-Mojolicious-Plugin-AssetPack.noarch : Compress and convert CSS, Less, Sass, JavaScript and CoffeeScript files
rubygem-compass-import-once.noarch : Speed up your Sass compilation by making @import only import each file once
[kushal@ideapadflex-kushal openroom]$ dnf info libsass
Last metadata expiration check: 0:00:47 ago on Wed 08 Apr 2020 07:18:34 PM MDT.
Available Packages
Name         : libsass
Version      : 3.5.5
Release      : 2.fc31
Architecture : i686
Size         : 987 k
Source       : libsass-3.5.5-2.fc31.src.rpm
Repository   : fedora
Summary      : C/C++ port of the Sass CSS precompiler
URL          : http://sass-lang.com/libsass
License      : MIT
Description  : Libsass is a C/C++ port of the Sass CSS precompiler. The original version was
             : written in Ruby, but this version is meant for efficiency and portability.
             :
             : This library strives to be light, simple, and easy to build and integrate with
             : a variety of platforms and languages.
             :
             : Libsass is just a library, but if you want to RUN libsass, install the sassc
             : package.

Name         : libsass
Version      : 3.5.5
Release      : 2.fc31
Architecture : x86_64
Size         : 940 k
Source       : libsass-3.5.5-2.fc31.src.rpm
Repository   : fedora
Summary      : C/C++ port of the Sass CSS precompiler
URL          : http://sass-lang.com/libsass
License      : MIT
Description  : Libsass is a C/C++ port of the Sass CSS precompiler. The original version was
             : written in Ruby, but this version is meant for efficiency and portability.
             :
             : This library strives to be light, simple, and easy to build and integrate with
             : a variety of platforms and languages.
             :
             : Libsass is just a library, but if you want to RUN libsass, install the sassc
             : package.

[kushal@ideapadflex-kushal openroom]$ npm uninstall -g sass
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.1.2 (node_modules/sass/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

removed 15 packages in 0.406s
[kushal@ideapadflex-kushal openroom]$ script -a ~/log/$(date -u +%FT%H%M%Z).logScript started, file is /home/kushal/log/2020-04-09T0121UTC.log[kushal@ideapadflex-kushal openroom]$ pwd
/home/kushal/src/php/openroom
[kushal@ideapadflex-kushal openroom]$ sass themes/kushal/assets/sass/hello.sass themes/kushal/assets/sass/hello.css
bash: sass: command not found...
Install package 'rubygem-sass' to provide command 'sass'? [N/y]

[kushal@ideapadflex-kushal openroom]$ time dnf info sassc
Last metadata expiration check: 0:04:04 ago on Wed 08 Apr 2020 07:18:34 PM MDT.
Available Packages
Name         : sassc
Version      : 3.5.0
Release      : 2.fc30
Architecture : x86_64
Size         : 18 k
Source       : sassc-3.5.0-2.fc30.src.rpm
Repository   : fedora
Summary      : Wrapper around libsass to compile CSS stylesheet
URL          : http://github.com/sass/sassc
License      : MIT
Description  : SassC is a wrapper around libsass used to generate a useful command-line
             : application that can be installed and packaged for several operating systems.

real    0m2.497s
user    0m2.312s
sys     0m0.137s
[kushal@ideapadflex-kushal openroom]$ time sudo dnf info sassc
[sudo] password for kushal:
Last metadata expiration check: 1:56:49 ago on Wed 08 Apr 2020 05:26:01 PM MDT.
Available Packages
Name         : sassc
Version      : 3.5.0
Release      : 2.fc30
Architecture : x86_64
Size         : 18 k
Source       : sassc-3.5.0-2.fc30.src.rpm
Repository   : fedora
Summary      : Wrapper around libsass to compile CSS stylesheet
URL          : http://github.com/sass/sassc
License      : MIT
Description  : SassC is a wrapper around libsass used to generate a useful command-line
             : application that can be installed and packaged for several operating systems.

real    0m6.884s
user    0m2.662s
sys     0m0.223s
[kushal@ideapadflex-kushal openroom]$ time sudo dnf install sassc
Last metadata expiration check: 1:57:02 ago on Wed 08 Apr 2020 05:26:01 PM MDT.
Dependencies resolved.
======================================================================================================================================================================================
 Package                                  Architecture                              Version                                           Repository                                 Size
======================================================================================================================================================================================
Installing:
 sassc                                    x86_64                                    3.5.0-2.fc30                                      fedora                                     18 k

Transaction Summary
======================================================================================================================================================================================
Install  1 Package

Total download size: 18 k
Installed size: 34 k
Is this ok [y/N]: y
Downloading Packages:
sassc-3.5.0-2.fc30.x86_64.rpm                                                                                                                          31 kB/s |  18 kB     00:00
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Total                                                                                                                                                  20 kB/s |  18 kB     00:00
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Preparing        :                                                                                                                                                              1/1
  Installing       : sassc-3.5.0-2.fc30.x86_64                                                                                                                                    1/1
  Running scriptlet: sassc-3.5.0-2.fc30.x86_64                                                                                                                                    1/1
  Verifying        : sassc-3.5.0-2.fc30.x86_64                                                                                                                                    1/1

Installed:
  sassc-3.5.0-2.fc30.x86_64

Complete!

real    0m9.572s
user    0m4.262s
sys     0m0.310s
[kushal@ideapadflex-kushal openroom]$ sass themes/kushal/assets/sass/hello.sass themes/kushal/assets/sass/hello.css
bash: sass: command not found...
Install package 'rubygem-sass' to provide command 'sass'? [N/y]

[kushal@ideapadflex-kushal openroom]$ time sudo dnf remove sassc libsass
Dependencies resolved.
======================================================================================================================================================================================
 Package                                   Architecture                             Version                                           Repository                                 Size
======================================================================================================================================================================================
Removing:
 libsass                                   x86_64                                   3.5.5-2.fc31                                      @fedora                                   3.7 M
 sassc                                     x86_64                                   3.5.0-2.fc30                                      @fedora                                    34 k

Transaction Summary
======================================================================================================================================================================================
Remove  2 Packages

Freed space: 3.7 M
Is this ok [y/N]: y
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Preparing        :                                                                                                                                                              1/1
  Erasing          : sassc-3.5.0-2.fc30.x86_64                                                                                                                                    1/2
  Erasing          : libsass-3.5.5-2.fc31.x86_64                                                                                                                                  2/2
  Running scriptlet: libsass-3.5.5-2.fc31.x86_64                                                                                                                                  2/2
  Verifying        : libsass-3.5.5-2.fc31.x86_64                                                                                                                                  1/2
  Verifying        : sassc-3.5.0-2.fc30.x86_64                                                                                                                                    2/2

Removed:
  libsass-3.5.5-2.fc31.x86_64                                                                sassc-3.5.0-2.fc30.x86_64

Complete!

real    0m3.254s
user    0m0.911s
sys     0m0.164s
[kushal@ideapadflex-kushal openroom]$ time sudo dnf install sassc
Last metadata expiration check: 1:59:28 ago on Wed 08 Apr 2020 05:26:01 PM MDT.
Dependencies resolved.
======================================================================================================================================================================================
 Package                                    Architecture                              Version                                         Repository                                 Size
======================================================================================================================================================================================
Installing:
 sassc                                      x86_64                                    3.5.0-2.fc30                                    fedora                                     18 k
Installing dependencies:
 libsass                                    x86_64                                    3.5.5-2.fc31                                    fedora                                    940 k

Transaction Summary
======================================================================================================================================================================================
Install  2 Packages

Total download size: 958 k
Installed size: 3.7 M
Is this ok [y/N]: y
Downloading Packages:
(1/2): sassc-3.5.0-2.fc30.x86_64.rpm                                                                                                                   26 kB/s |  18 kB     00:00
(2/2): libsass-3.5.5-2.fc31.x86_64.rpm                                                                                                                640 kB/s | 940 kB     00:01
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Total                                                                                                                                                 493 kB/s | 958 kB     00:01
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Preparing        :                                                                                                                                                              1/1
  Installing       : libsass-3.5.5-2.fc31.x86_64                                                                                                                                  1/2
  Installing       : sassc-3.5.0-2.fc30.x86_64                                                                                                                                    2/2
  Running scriptlet: sassc-3.5.0-2.fc30.x86_64                                                                                                                                    2/2
  Verifying        : libsass-3.5.5-2.fc31.x86_64                                                                                                                                  1/2
  Verifying        : sassc-3.5.0-2.fc30.x86_64                                                                                                                                    2/2

Installed:
  libsass-3.5.5-2.fc31.x86_64                                                                sassc-3.5.0-2.fc30.x86_64

Complete!

real    0m10.019s
user    0m4.294s
sys     0m0.386s
[kushal@ideapadflex-kushal openroom]$ which sass
/usr/bin/which: no sass in (/home/kushal/.nvm/versions/node/v13.12.0/bin:/home/kushal/.local/bin:/home/kushal/bin:/usr/share/Modules/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/home/kushal/.composer/vendor/bin:/home/kushal/.dotnet/tools:/home/kushal/.dotnet/tools:/home/kushal/.dotnet/tools:/home/kushal/.dotnet/tools:/home/kushal/.dotnet/tools)
[kushal@ideapadflex-kushal openroom]$ which sassc
/usr/bin/sassc
[kushal@ideapadflex-kushal openroom]$ sassc themes/kushal/assets/sass/hello.sass themes/kushal/assets/sass/hello.css
[kushal@ideapadflex-kushal openroom]$ sassc themes/kushal/assets/sass/hello.sass themes/kushal/assets/sass/hello.css
[kushal@ideapadflex-kushal openroom]$ ^C
[kushal@ideapadflex-kushal openroom]$